version: '3'
services:
  reddcoin-core:
    container_name: reddcoin-core
    build:
      context: ./
      dockerfile: Dockerfile-reddcore
    volumes:
    - ./redd-data-dir/:/root/.reddcoin/
    networks:
     net1:
       aliases:
        - alias2
    ports:
     - 0.0.0.0:45444:45444
     - 0.0.0.0:45443:45443

networks:
  net1:
